### ISSUE TITLE
[DEV] Non-Block Wires Do Not Save Properly

### ISSUE THREAD

**Issue by roryyamm** [patryk3211/PowerGrid#195]
### Description

I have managed to build a transmission line across my world, and I was pretty stoked that it managed to get power to three different accumulators at wildly different points simultaneously without some sort of crash. I exited the world and re-entered to see if it would persist, but I was disappointed to find that the wires no longer carried any power outside of the chunkloaded portion near the power station. Even just outside chunkloader range was no good for power. 

Snipping and re-wiring the connection from the nearest terminals with voltage to the closest place that accepted power (wouldn't you know, it's the connector for the accumulator on that fucking bridge) resulted in those wires carrying power once more, however the wires beyond it that I had yet to re-do were still not carrying power. 

<img width="3200" height="2400" alt="Image" src="https://github.com/user-attachments/assets/64d56495-99e1-47b8-b565-6b9985e593b1" />

Exiting and re-entering resets the wires again, requiring re-wiring. 

### Game Log

https://mclo.gs/jXhR0SP (LATEST) https://mclo.gs/VLHsFdL (DEBUG)

**Comment by roryyamm** [comment]
This appears to be a counterpart to #191, adjusting name to match.

**Comment by patryk3211** [comment]
I believe this should be fixed now.

**Comment by roryyamm** [comment]
I cannot test it, due to a new crash - I'll get you the crash log in a new issue.

**Comment by roryyamm** [comment]
Issue is not fixed when testing in a different world. Upon building a new transmission line, and exiting and re-entering, a new crash report comes up, one I've been battling for a while now - `both nodes of a wire must be part of the network`. 
https://mclo.gs/Z6CFEYD (CRASH)
https://mclo.gs/2CsJMRd (LATEST)
https://mclo.gs/teRKNLI (DBG)
However, reloading the world a second time reveals the transmission line is 1) fine, save for a segment and 2) works well once the segment is reconnected.

**Comment by roryyamm** [comment]
The issue is not completely fixed. I found issues with wires not being saved _as I was placing them,_ then when trying to replace them, eventually ran into a situation where, for one of the lines, I'd replace a wire, and find that the segment going towards the power source just burned and disappeared. Chasing the wire back, I eventually ran into this fun crash. 

https://mclo.gs/o4Hsvj1 (CRASH)
https://mclo.gs/6w8KkW5 (LATEST)
https://mclo.gs/Dym1C1J (DBG)

**Comment by patryk3211** [comment]
I've changed a thing and enabled some more logging. Please try to reproduce the issue and send a new debug log.

**Comment by roryyamm** [comment]
Will do. I did put a few comments in chat, indicating what I was doing. Look for 
`will now exit the world and re-enter to test its persistence and give a good debug log` to see where I close the world and re-enter.
https://mclo.gs/2w73vVz (DBG)
There is a LOT of 'unresolving' going on in the debug log at save time on both occasions of level exit. Perhaps that's the issue? 
For completion's sake, the latest as well. 
https://mclo.gs/wNibXru (LATEST)

**Comment by roryyamm** [comment]
Interestingly, when you delete the nbt file, start from parts of a network that _are_ recognized as carrying current, and slowly go across the network to parts that _aren't_, the network data apparently rebuilds just fine. However, doing the opposite results in something far less functional. My guess is, the code is extendintg things as they're loaded, and if you're standing around a bunch of 'dud' cables when it comes time to re-construct the NBT file, it'll start adding on the ones it loads to said dud cables.

**Comment by roryyamm** [comment]
If you want my personal opinion, this is the second mod I've used that tries to pull off multi-kilometer wire networks. The first was [Pantographs & Wires](https://github.com/MisterJulsen/Create-Pantographs-and-Wires). That mod was far more NBT-dependent - you delete the `pantographsandwires_wire_network.nbt` file from your data folder, your wire network is completely gone. I should know; it was something I kept running into when I was playing around with its first release, since every wire simply failed to save on exit. But when that issue was fixed, it was rock-solid. 

[pantographsandwires_wire_network.nbt.txt](https://github.com/user-attachments/files/22103821/pantographsandwires_wire_network.nbt.txt)

This mod seems to use a hybrid system for wires. The data that says how the wire ties in to the network is in the DAT file, but the wire itself seems to be saved into the world somehow. That architecture might be causing these issues. Block wires, I don't know of much of an alternative to storing it in the world. But for the free-flying wires in this issue, you might be able to get away with something more akin to P&W's solution, where the existence of the wires are entirely dependent on their existence in the NBT file. I don't know if that's technically feasible in this mod - I mean, I barely managed to bodge together removing dynamic stress on my own, I'm absolutely hopeless when it comes to figuring out the technical foundations of this mod - but it might be worth looking into.

**Comment by patryk3211** [comment]
From my limited testing, the lines seems to save and load back correctly now.

**Comment by roryyamm** [comment]
I can confirm that the lines do save more properly. When I start where there isn't power, travel until there is power, and then return, the lines realize they carry power. Systems charge and wires carry voltage, without having to snip wires or delete files. 

I don't know if that's sufficient to call this 'fixed' - I do still have to travel along the line until I see one of the voltmeters has power, then travel back along the line to the point where power is needed to make it transmit power - but this might be fixed enough for v0.2.0. Feel free to close the issue if that is the case.  

https://mclo.gs/mlBm1qg (DBG)
https://mclo.gs/2ytaCos (LATEST)

**Comment by patryk3211** [comment]
I get the feeling that I'll have to rewrite all of the transmission line code. Right now I believe some issues might be caused by multi-block entities (windings, batteries). I'll figure this out and then, for now, I think these lines should work well enough.

**Comment by patryk3211** [comment]
Alright, after a somewhat major rework of the save format, I'm almost certain that this should work well now. You will however have to fly around your world and load back all the lines at first.
Edit: Well, it seems like transformers are still causing some issues

**Comment by roryyamm** [comment]
Well, I'll be. It works like a charm. I and anyone else who wants to build gigantic world-spanning transmission networks can rest assured that their electrical supply isn't dependent on whether there's someone walking under the power lines all the time.
