### ISSUE TITLE
Crash when attempting to press an ingot

### ISSUE THREAD

**Issue by Derpford** [patryk3211/PowerGrid#291]
### Description

When a mechanical press is trying to press an iron ingot, the game crashes.

### Game Log

https://mclo.gs/oqtG1Yt

**Comment by patryk3211** [comment]
Thank you for the report, the issue has been resolved and the fix will be available in the next update

**Comment by PublicVoidUpdate** [comment]
[crash-2026-03-07_22.55.23-server.txt](https://github.com/user-attachments/files/25821818/crash-2026-03-07_22.55.23-server.txt)
On the newest Modrinth (0.5.4) 1.20.1 Fabric this issue persists and might have borked my save :(

**Comment by patryk3211** [comment]
Use github actions build
